### ISSUE TITLE
Folder identifier strategy

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-workspace-server#10]
Unlike templates, elements, fields and instances, folders resolution (through the @id field) is dependent on name of the host that created them. If this host name changes, folder resolution breaks. 

We need to decide on a folder identifier/resolution approach the is not host name dependent.

**Comment by martinjoconnor** [comment]
@egyedia I think you have fixed this?

**Comment by egyedia** [comment]
It is done.
