### ISSUE TITLE
Document permissions

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-workspace-server#12]

**Comment by marcosmro** [comment]
Some ideas:
http://cdn.makeuseof.com/wp-content/uploads/2015/11/Google-Drive-Sharing-Access.jpg?x92042
https://img.scoop.it/MhmOFZVb0zTFi1r-k9itQzl72eJkfbmt4t8yenImKBVvK0kTmF0xjctABnaLJIm9

**Comment by egyedia** [comment]
The document can be found here:
https://docs.google.com/document/d/1Sdf0xprFJ24lyg_dEINZyQs9okecB_qZOuUr-WLCBDA/edit
